// Generated by tools/icon-sync/sync.mjs from categories.json. Do not edit.
package com.bond.mail.data.mail

internal object GenericSenderCategories {
    data class Entry(val category: String, val domains: List<String>, val names: List<String>, val exactNames: List<String>)
    val entries = listOf(
        Entry("bank", listOf("maya.ph", "mayabank.ph"), listOf("maya bank", "paymaya", "maya philippines"), listOf("maya")),
        Entry("bank", listOf("gotyme.com.ph"), listOf("gotyme"), listOf()),
        Entry("bank", listOf("tonikbank.com"), listOf("tonik"), listOf()),
        Entry("bank", listOf("cimbbank.com.ph"), listOf("cimb"), listOf()),
        Entry("bank", listOf("bdo.com.ph"), listOf("bdo unibank"), listOf("bdo")),
        Entry("bank", listOf("bpi.com.ph"), listOf("bank of the philippine islands"), listOf("bpi")),
        Entry("bank", listOf("rcbc.com"), listOf("rcbc"), listOf()),
        Entry("bank", listOf("dbs.com"), listOf("dbs bank", "星展"), listOf("dbs")),
        Entry("bank", listOf("ocbc.com"), listOf("ocbc", "华侨银行", "華僑銀行"), listOf()),
        Entry("bank", listOf("uob.com.sg"), listOf("uob", "大华银行", "大華銀行"), listOf()),
        Entry("simcard", listOf("saily.com"), listOf("saily"), listOf()),
        Entry("simcard", listOf("m1.com.sg"), listOf("m1 singapore"), listOf("m1")),
        Entry("simcard", listOf("giga.com.sg"), listOf("giga mobile"), listOf("giga", "giga!")),
        Entry("simcard", listOf("gomo.sg"), listOf("gomo"), listOf()),
        Entry("simcard", listOf("maya.net"), listOf("maya mobile", "maya esim"), listOf()),
        Entry("sports", listOf("reebok.com"), listOf("reebok", "锐步", "銳步"), listOf("reebok")),
        Entry("sports", listOf("hoka.com"), listOf("hoka"), listOf("hoka")),
        Entry("sports", listOf("brooksrunning.com"), listOf("brooks running", "布鲁克斯"), listOf("brooks")),
        Entry("sports", listOf("fila.com"), listOf("fila", "斐乐", "斐樂"), listOf("fila")),
        Entry("sports", listOf("converse.com"), listOf("converse shoes", "匡威"), listOf("converse")),
        Entry("sports", listOf("vans.com"), listOf("vans shoes", "范斯"), listOf("vans")),
        Entry("clothes", listOf("zara.com"), listOf("zara"), listOf("zara")),
        Entry("clothes", listOf("hm.com"), listOf("h&m", "hennes & mauritz"), listOf("h&m")),
        Entry("clothes", listOf("gap.com"), listOf("gap clothing", "gap store"), listOf("gap")),
        Entry("clothes", listOf("levi.com"), listOf("levi's", "levi’s", "levis", "李维斯", "李維斯"), listOf("levis")),
        Entry("clothes", listOf("mango.com"), listOf("mango fashion"), listOf("mango")),
        Entry("exchange", listOf("bitpanda.com"), listOf("bitpanda"), listOf()),
        Entry("exchange", listOf("bitunix.com"), listOf("bitunix"), listOf()),
    )
    private val patterns = entries.map { entry ->
        entry to entry.names.map { name ->
            Regex("(?<![a-z0-9])" + Regex.escape(name.lowercase()) + "(?![a-z0-9])")
        }
    }
    fun byDomain(domain: String): BrandMatcher.Brand? = entries.firstOrNull { entry ->
        entry.domains.any { domain == it || domain.endsWith(".$it") }
    }?.let { brand(it.category) }
    fun byName(name: String): BrandMatcher.Brand? = patterns.firstOrNull { (entry, expressions) ->
        name in entry.exactNames || expressions.any { it.containsMatchIn(name) }
    }?.first?.let { brand(it.category) }
    private fun brand(category: String) = BrandMatcher.Brand(category, when (category) {
        "bank" -> "BANK"
        "simcard" -> "SIM"
        "sports" -> "SPORT"
        "clothes" -> "WEAR"
        else -> "EX"
    })
}
