import { readFile, writeFile, mkdir, readdir, access, unlink } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const assets = path.join(root, 'app/src/main/assets/contact_logos');
const catalog = JSON.parse(await readFile(path.join(here, 'catalog.json'), 'utf8'));
const output = path.join(assets, 'thesvg');
const localOutput = path.join(assets, 'local');
await mkdir(output, { recursive: true });
await mkdir(localOutput, { recursive: true });
const exists = async p => access(p).then(() => true, () => false);
const normalize = name => name.toLowerCase().replace(/[^a-z0-9]/g, '');
const locals = await readdir(path.join(root, 'ICON')).catch(() => []);
const knownAssets = (await readdir(assets)).filter(n => n.endsWith('.svg'));
// Auto-sync source files whose names match established Android asset keys.
for (const filename of locals.filter(n => n.endsWith('.svg'))) {
  const key = knownAssets.find(n => normalize(n) === normalize(filename))?.slice(0, -4);
  if (key && !catalog[key]) catalog[key] = { local: filename, domains: [] };
}
// One checked registry feeds both the avatar domain aliases and the pure Kotlin matcher.
const categories = JSON.parse(await readFile(path.join(here, 'categories.json'), 'utf8'));
const categoryKeys = new Set(['bank', 'simcard', 'sports', 'clothes', 'exchange']);
const categoryDomains = new Map();
for (const entry of categories) {
  if (!categoryKeys.has(entry.category)) throw new Error(`Invalid category: ${entry.category}`);
  if (!await exists(path.join(assets, `${entry.category}.svg`))) throw new Error(`Missing category asset: ${entry.category}`);
  for (const domain of entry.domains) {
    if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain) || categoryDomains.has(domain)) throw new Error(`Invalid/duplicate domain: ${domain}`);
    categoryDomains.set(domain, entry.category);
  }
  catalog[entry.category] ??= { domains: [] };
  catalog[entry.category].domains = [...new Set([...catalog[entry.category].domains, ...entry.domains])];
}
const kotlinString = value => JSON.stringify(value).replaceAll('$', '\\$');
const kotlinList = values => `listOf(${values.map(kotlinString).join(', ')})`;
const generated = `// Generated by tools/icon-sync/sync.mjs from categories.json. Do not edit.
package com.bond.mail.data.mail

internal object GenericSenderCategories {
    data class Entry(val category: String, val domains: List<String>, val names: List<String>, val exactNames: List<String>)
    val entries = listOf(
${categories.map(e => `        Entry(${kotlinString(e.category)}, ${kotlinList(e.domains)}, ${kotlinList(e.names)}, ${kotlinList(e.exactNames)}),`).join('\n')}
    )
    private val patterns = entries.map { entry ->
        entry to entry.names.map { name ->
            Regex("(?<![a-z0-9])" + Regex.escape(name.lowercase()) + "(?![a-z0-9])")
        }
    }
    fun byDomain(domain: String): BrandMatcher.Brand? = entries.firstOrNull { entry ->
        entry.domains.any { domain == it || domain.endsWith(".$it") }
    }?.let { brand(it.category) }
    fun byName(name: String): BrandMatcher.Brand? = patterns.firstOrNull { (entry, expressions) ->
        name in entry.exactNames || expressions.any { it.containsMatchIn(name) }
    }?.first?.let { brand(it.category) }
    private fun brand(category: String) = BrandMatcher.Brand(category, when (category) {
        "bank" -> "BANK"
        "simcard" -> "SIM"
        "sports" -> "SPORT"
        "clothes" -> "WEAR"
        else -> "EX"
    })
}
`;
await writeFile(path.join(root, 'app/src/main/java/com/bond/mail/data/mail/GenericSenderCategories.kt'), generated);

const domains = {};
const report = [];
for (const [key, entry] of Object.entries(catalog).sort()) {
  if (!/^[a-z0-9._-]+$/.test(key)) throw new Error(`Invalid asset key: ${key}`);
  // Root assets are curated for this renderer (backgrounds removed, paths repaired).
  // Keep them authoritative and remove only generated duplicates owned by this tool.
  if (await exists(path.join(assets, `${key}.svg`))) {
    for (const generated of [localOutput, output]) {
      const duplicate = path.join(generated, `${key}.svg`);
      if (await exists(duplicate)) await unlink(duplicate);
    }
    for (const domain of entry.domains) domains[domain] = key;
    report.push({ key, source: `contact_logos/${key}.svg (curated)` });
    continue;
  }
  let svg, source, destination, license, upstreamUrl;
  if (entry.local && await exists(path.join(root, 'ICON', entry.local))) {
    svg = await readFile(path.join(root, 'ICON', entry.local), 'utf8');
    source = `ICON/${entry.local}`;
    destination = localOutput;
  } else if (entry.slug) {
    const { default: icon } = await import(`@thesvg/icons/${entry.slug}`);
    svg = icon.variants.mono || icon.svg;
    source = `@thesvg/icons/${entry.slug} (${icon.variants.mono ? 'mono' : 'default'})`;
    license = icon.license;
    upstreamUrl = icon.url;
    destination = output;
  } else continue;
  if (entry.removeBackgroundCircle) svg = svg.replace(/<circle\b[^>]*\/?\s*>/g, '');
  if (!svg.includes('<svg') || /<script\b|<foreignObject\b/i.test(svg)) throw new Error(`Invalid SVG: ${key}`);
  await writeFile(path.join(destination, `${key}.svg`), svg.trim() + '\n');
  // Only remove this tool's same-key generated counterpart, never hand-maintained overrides.
  const counterpart = path.join(destination === output ? localOutput : output, `${key}.svg`);
  if (await exists(counterpart)) await unlink(counterpart);
  for (const domain of entry.domains) domains[domain] = key;
  report.push({ key, source, license, upstreamUrl });
}
// Keep one SVG per asset key in the same priority order as the Android loader.
// License/attribution files are retained in every source directory.
const seen = new Set();
for (const directory of [assets, localOutput, output, path.join(assets, 'simpleicons')]) {
  for (const name of (await readdir(directory).catch(() => [])).filter(n => n.endsWith('.svg'))) {
    if (seen.has(name)) await unlink(path.join(directory, name));
    else seen.add(name);
  }
}
await writeFile(path.join(assets, 'domains.json'), JSON.stringify(domains, null, 2) + '\n');
await writeFile(path.join(output, 'sources.json'), JSON.stringify(report, null, 2) + '\n');
console.log(`Synced ${report.length} icons and ${Object.keys(domains).length} domains; existing overrides preserved.`);
